### ISSUE TITLE
What are good options for an accompanying PICO atx psu?

### ISSUE THREAD

**Issue by perchrh** [dekuNukem/ATX4VC#1]

**Comment by dekuNukem** [comment]
I would suggest using the official one. [Website](https://www.mini-box.com/DC-DC) and [distributors](https://www.mini-box.com/site/resellers.html). Even the cheapest 80W one should be plenty.

You can also find generic ones on eBay/Amazon/Aliexpress by searching `Pico ATX`. They are *not that* cheap, so might be better to stick with the high-quality ones above.
